// <auto-generated />
using CarStockDAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarStockDAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241212113841_NewStructure")]
    partial class NewStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarStockDAL.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audi"
                        });
                });

            modelBuilder.Entity("CarStockDAL.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvaible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CarModelId");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarStockDAL.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "Camry"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "RAV4"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "X5"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            Name = "3 Series"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Name = "5 Series"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 3,
                            Name = "911 Carrera"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            Name = "Cayenne"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Name = "Macan"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 4,
                            Name = "C-Class"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 4,
                            Name = "E-Class"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 4,
                            Name = "GLE"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 4,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 4,
                            Name = "Q5"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            Name = "A6"
                        });
                });

            modelBuilder.Entity("CarStockDAL.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 4,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 4,
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 5,
                            Name = "Grey"
                        },
                        new
                        {
                            Id = 4,
                            CarModelId = 5,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 5,
                            CarModelId = 6,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 6,
                            CarModelId = 6,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 7,
                            CarModelId = 7,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 8,
                            CarModelId = 7,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 9,
                            CarModelId = 8,
                            Name = "White"
                        },
                        new
                        {
                            Id = 10,
                            CarModelId = 8,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 11,
                            CarModelId = 9,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 12,
                            CarModelId = 9,
                            Name = "Blue"
                        });
                });

            modelBuilder.Entity("CarStockDAL.Models.Car", b =>
                {
                    b.HasOne("CarStockDAL.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarStockDAL.Models.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarStockDAL.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("CarModel");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("CarStockDAL.Models.CarModel", b =>
                {
                    b.HasOne("CarStockDAL.Models.Brand", "Brand")
                        .WithMany("CarsModel")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarStockDAL.Models.Color", b =>
                {
                    b.HasOne("CarStockDAL.Models.CarModel", "CarModel")
                        .WithMany("Colors")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("CarStockDAL.Models.Brand", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("CarsModel");
                });

            modelBuilder.Entity("CarStockDAL.Models.CarModel", b =>
                {
                    b.Navigation("Colors");
                });
#pragma warning restore 612, 618
        }
    }
}
