// <auto-generated />
using CarStockDAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarStockDAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarStockDAL.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 0,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 0,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 0,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 0,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 0,
                            Name = "Audi"
                        });
                });

            modelBuilder.Entity("CarStockDAL.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId")
                        .IsUnique();

                    b.HasIndex("ColorId")
                        .IsUnique();

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarStockDAL.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 0,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 0,
                            Name = "Camry"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 0,
                            Name = "RAV4"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 0,
                            Name = "X5"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 0,
                            Name = "3 Series"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 0,
                            Name = "5 Series"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 0,
                            Name = "911 Carrera"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 0,
                            Name = "Cayenne"
                        },
                        new
                        {
                            Id = 9,
                            CarId = 0,
                            Name = "Macan"
                        },
                        new
                        {
                            Id = 10,
                            CarId = 0,
                            Name = "C-Class"
                        },
                        new
                        {
                            Id = 11,
                            CarId = 0,
                            Name = "E-Class"
                        },
                        new
                        {
                            Id = 12,
                            CarId = 0,
                            Name = "GLE"
                        },
                        new
                        {
                            Id = 13,
                            CarId = 0,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 14,
                            CarId = 0,
                            Name = "Q5"
                        },
                        new
                        {
                            Id = 15,
                            CarId = 0,
                            Name = "A6"
                        });
                });

            modelBuilder.Entity("CarStockDAL.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 0,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 0,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 0,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 0,
                            Name = "White"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 0,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 0,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 0,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 0,
                            Name = "Gray"
                        });
                });

            modelBuilder.Entity("CarStockDAL.Models.Car", b =>
                {
                    b.HasOne("CarStockDAL.Models.Brand", "Brand")
                        .WithOne("Car")
                        .HasForeignKey("CarStockDAL.Models.Car", "BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarStockDAL.Models.Color", "Color")
                        .WithOne("Car")
                        .HasForeignKey("CarStockDAL.Models.Car", "ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarStockDAL.Models.CarModel", "Model")
                        .WithOne("Car")
                        .HasForeignKey("CarStockDAL.Models.Car", "ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarStockDAL.Models.Brand", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStockDAL.Models.CarModel", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("CarStockDAL.Models.Color", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
